from pathlib import Path
import os
from dotenv import load_dotenv
 
load_dotenv()
 
# Folder to watch
WATCH_FOLDER = Path(os.environ['MOUNT_POINT']) / os.environ['SUBDIR_SRC']
OUTPUT_FOLDER = Path(os.environ['MOUNT_POINT']) / os.environ['SUBDIR_DEST']
 
# Keywords for detection
KEYWORDS = ["opgebeld", "telefoon", "card", "bankkaart", "koerier"]
 
# Character replacements for encoding issues
REPLACEMENTS = {
    "Ã©": "é",
    "Ã‰": "É",
    "Ã«": "ë",
    "Â°": "°",
    "Â¦": "¦",
    "Ã¶": "ö",
    "Ãœ": "Ü",
    "Ã¼": "ü",
    "Ã¨": "è",
    "Ã‡": "Ç",
    "Ã‹": "Ë",
    "Â²": "²",
    "Ã¯": "ï",
    "Ã§": "ç",
    "Ã¡": "á",
    "Ã–": "Ö",
    "Ã³": "ó",
    "Ãˆ": "È",
    "Ã´": "ô",
    "Ãª": "ê",
}
 
# Dictionary of RefGeb codes and descriptions
REFGEB_CODES = {
    "A":"Arrestatie / Aanhouding",
    "A01":"Onderzoek  Politie",
    "A0101":"Autopsie",
    "A011":"Verhoor",
    "A0111":"Salduz-wetgeving",
    "A0112":"Videoverhoor",
    "A0113":"Weigering uithaling",
    "A0114":"Schriftproef",
    "A012":"Buurtonderzoek",
    "A013":"Retro gevraagd",
    "A014":"Tap gevraagd",
    "A0141":"Opvolging tap",
    "A0142":"Stopzetting tap",
    "A0143":"Resultaten Tap",
    "A015":"Telefoon obs nice",
    "A016":"Zendmastverkeer",
    "A017":"Afstapping",
    "A018":"Getuige",
    "A019":"uitlezen PC-GSM-tablet",
    "A02":"Camerabeelden",
    "A0201":"ANPR",
    "A021":"Imei-track gevraagd",
    "A05":"Daden dader",
    "A051":"Gestolen",
    "A052":"Teruggevonden",
    "A053":"Vernield",
    "A054":"Gedumpt",
    "A055":"Vervalst",
    "A056":"Poging",
    "A0901":"Neerlegging",
    "A0902":"Teruggave IBN",
    "A1":"Bevel tot medebrenging uitvaardiging",
    "A11":"Bevel tot medebrenging betekening",
    "A2":"Bevel tot aanhouding uitvaardiging",
    "A21":"Bevel tot aanhouding betekening",
    "A3":"Seining nationaal",
    "A31":"Ontseining Nationaal",
    "A4":"Seining Shengen",
    "A41":"Ontseining Shengen",
    "A42":"PGP / onderzoek lopend",
    "A43":"PGP / effectief",
    "A44":"PGP / aangevraagd",
    "A5":"Seining internationaal",
    "A51":"Ontseining Internationaal",
    "A6":"Herkenning fotodossier",
    "A61":"Herkenning fotodossier negatief",
    "A62":"Weigering fotoboek te bekijken",
    "A7":"Herkenning line-up",
    "A71":"Herkenning line-up negatief",
    "A8":"Huiszoeking",
    "A81":"HZ toestemming",
    "A82":"Bevel huiszoeking",
    "A83":"HZ Heterdaad",
    "A9":"Inbeslagname",
    "A901":"Neerlegging",
    "B":"Buitenland",
    "B1":"Europa",
    "B101":"Nederland",
    "B102":"Verenigd Koninkrijk",
    "B1021":"England",
    "B1022":"Wales",
    "B1023":"Schotland",
    "B1024":"Noord-Ierland",
    "B103":"Duitsland",
    "B104":"Frankrijk",
    "B105":"Luxemburg",
    "B106":"Zwitserland",
    "B107":"Spanje",
    "B108":"Italië",
    "B109":"Polen",
    "B110":"Moldavië",
    "B111":"Ierland",
    "B112":"Albanië",
    "B113":"Wit-Rusland",
    "B114":"Oekraïne",
    "B115":"Griekenland",
    "B116":"Monaco",
    "B117":"Slovenië",
    "B118":"Estland",
    "B119":"Letland",
    "B120":"Rusland",
    "B121":"Tsjechië",
    "B122":"Roemenië",
    "B123":"Oostenrijk",
    "B124":"Hongarije",
    "B125":"Turkije",
    "B126":"Zweden",
    "B127":"Oost-Europa",
    "B128":"België",
    "B1281":"Noord Limburg",
    "B1282":"Zuid Limburg",
    "B1283":"Midden Limburg",
    "B1284":"Oost Limburg",
    "B1285":"West Limburg",
    "B1286":"Luik",
    "B1287":"Antwerpen",
    "B129":"Bulgarije",
    "B130":"Slovakije",
    "B131":"Malta",
    "B132":"Monte-Negro",
    "B133":"Servië",
    "B134":"Litouwen",
    "B135":"Macedonië",
    "B136":"Portugal",
    "B137":"Noorwegen",
    "B2":"Afrika",
    "B201":"Congo",
    "B202":"Ivoorkust",
    "B203":"Marokko",
    "B204":"Guinee",
    "B205":"Sierra Leone",
    "B206":"Senegal",
    "B207":"Zambia",
    "B3":"Azië",
    "B301":"Thailand",
    "B302":"China",
    "B303":"India",
    "B304":"Bhutan",
    "B305":"Singapore",
    "B306":"Libanon",
    "B307":"LAOS",
    "B308":"Israël",
    "B309":"Vietnam",
    "B310":"Syrie",
    "B311":"Afghanistan",
    "B312":"Tsjetjenie",
    "B313":"Verenigde Arabische Emiraten",
    "B3131":"Dubai",
    "B314":"Filipijnen",
    "B315":"Hong Kong",
    "B4":"Noord-Amerika",
    "B401":"Canada",
    "B402":"Verenigde Staten van Amerika",
    "B5":"Zuid-Amerika",
    "B501":"Nederlandse antillen",
    "B502":"Bolivia",
    "B503":"Equador",
    "B504":"Brazilïe",
    "B505":"Dominicaanse Republiek",
    "B506":"Argentinië",
    "B507":"Uruguay",
    "B508":"Columbia",
    "B509":"Panama",
    "B510":"Venezuela",
    "B511":"Chili",
    "B512":"Paraguay",
    "B513":"Guyana",
    "B514":"Frans-Guyana",
    "B515":"Suriname",
    "B516":"Peru",
    "B6":"Oceanïe",
    "B601":"Australië",
    "B602":"Nieuw-Zeeland",
    "C":"Commodities",
    "C001":"Horloge",
    "CYB001":"Ransomware",
    "CYB002":"Aankoop, verkoop en verhuur fraude",
    "CYB003":"Misbruik van identiteit",
    "CYB004":"Vriendschapsfraude",
    "CYB005":"BEC/CEO fraude",
    "CYB006":"Beleggingsfraude, loterij/erfenis fraude",
    "CYB007":"Whaling/Stranded Traveller",
    "CYB008":"Helpdeskfraude",
    "CYB009":"Phishing",
    "CYB010":"Misbruik online betalingsapps (vb. ApplePay)",
    "CYB011":"Diefstal virtuele munten, NFT",
    "CYB012":"Diefstal intellectuele eigendommen, liedjes, klantenbestanden, …",
    "CYB013":"Sextortion",
    "CYB014":"Voyeurisme / wraakporno",
    "CYB015":"Cyberlocking",
    "CYB016":"Diefstal ICT hardware",
    "CYB017":"Grooming",
    "CYB018":"Hacking/sabotage",
    "CYB019":"DDOS, sabotage",
    "CYB020":"Overname sociale media/website (celebrity, bedrijf, overname mailbox, …)",
    "D":"Drugs",
    "D01":"Softdrugs",
    "D02":"Coke / Cocaine",
    "D03":"Heroïne",
    "D04":"Synthetische drugs",
    "D041":"XTC",
    "D042":"Speed",
    "D043":"MDMA",
    "D043":"Ketamine",
    "D044":"Doping",
    "D05":"GHB",
    "D051":"Lachgas",
    "D06":"Cannabis / Weed",
    "D061":"Cannabisplantage",
    "D062":"Exploitant/organisator plantage",
    "D063":"Hasj",
    "D07":"Druglabo",
    "D071":"Laborant",
    "D072":"Bergplaats Drugs",
    "D073":"Tableteren",
    "D08":"Producten mbt productie drugs",
    "D080":"Methylamine",
    "D081":"BMK",
    "D082":"Methanol",
    "D083":"Formamide",
    "D084":"Mierezuur",
    "D085":"Platina Oxide",
    "D086":"Zwavelzuur",
    "D087":"Zoutzuur",
    "D088":"Apaan",
    "D089":"Olie",
    "D09":"Materialen mbt productie drugs",
    "D090":"Aceton",
    "D091":"Labo-afval / Dumping",
    "D092":"Insecticiden",
    "D100":"Drugs Dealer",
    "D200":"Drugs Internationaal",
    "D300":"Drugs Organisatie",
    "D301":"Drugs Organisator",
    "D302":"Drugs Koerier / transport",
    "D303":"Drugs Producent",
    "D304":"Drugs Gebruiker",
    "D320":"Dealplaats",
    "D321":"Drugs Gebruikplaats",
    "D350":"Drugs Prijzen",
    "E":"Misdrijf",
    "E01":"Diefstallen",
    "E012":"Winkeldiefstallen",
    "E013":"Autodiefstal",
    "E0131":"Gestolen",
    "E014":"Woninginbraak",
    "E015":"Ladingdiefstallen",
    "E0151":"Ladingdiefstal via snijden dekzeil",
    "E016":"Ramkraak",
    "E017":"Diefstal uit voertuig",
    "E02":"Mensenhandel",
    "E021":"Mensensmokkel",
    "E022":"Huisjesmelkerij",
    "E023":"Prostitutie",
    "E024":"Escorte",
    "E025":"Shemale - Ladyboy",
    "E03":"Heling",
    "E04":"Geweld / Bedreigingen",
    "E041":"ONTVOERING",
    "E042":"Gijzeling",
    "E05":"Corruptie",
    "E051":"Integriteit",
    "E08":"Financiële misdrijven",
    "E081":"Witwas",
    "E082":"",
    "E100":"Misdrijven andere",
    "E101":"Zwartwerk",
    "E102":"Schriftvervalsing",
    "E103":"Valsmunterij",
    "E104":"Verdachte handelingen",
    "E105":"brandstichting",
    "E106":"slagen en verwondingen",
    "E107":"Oplichting",
    "E108":"Afpersing",
    "E109":"Kunstmisdrijf",
    "E111":"Verdachte voertuigen",
    "E161":"Diefstal brandstof uit voertuig",
    "E190":"Diefstal rode mazout",
    "E200":"Bewijsmatrix",
    "E201":"Terro",
    "F":"Financieel",
    "F01":"Vastgoed/ onroerend goed",
    "F02":"Roerend goed",
    "F03":"Waardepapieren",
    "F04":"Cash Geld",
    "F041":"Geld in grond",
    "F042":"Stortingen cash geld",
    "F043":"Geldkoerier",
    "F044":"Losgeld",
    "F045":"CryptoCurrencies",
    "F05":"Inkomsten",
    "F06":"Uitgaven",
    "F07":"Schuld (financieel)",
    "F08":"Discrepantie",
    "F09":"Goud",
    "F091":"Tabak",
    "F092":"Mazout",
    "F093":"paarden",
    "F094":"duiven",
    "F10":"Bankrekeningen",
    "F101":"Overschrijving",
    "F11":"Boekhouding",
    "F20":"Kredietdossier",
    "F21":"Hypotheek",
    "F22":"investeringsdossier",
    "F30":"Geld transfer",
    "F40":"Bestuurder",
    "F41":"Zaakvoerder",
    "F42":"Mandataris",
    "F43":"Aandeelhouder",
    "F44":"Oprichter",
    "F45":"Volmachthouder",
    "F50":"Info Belastingen",
    "F60":"Nalatenschap",
    "F98":"Faillissement",
    "F99":"Beslag op financiële waarden",
    "Haven":"Haven",
    "I":"Inbeslagname",
    "K":"Kleur",
    "K01":"Rood",
    "K02":"Blauw",
    "K03":"Groen",
    "K04":"Geel",
    "K05":"Oranje",
    "K06":"Zwart",
    "K07":"Wit",
    "K08":"Bruin",
    "K09":"Grijs",
    "K091":"Zilvergrijs",
    "K10":"Paars",
    "K11":"Roze",
    "L001":"prive ontvangst",
    "L002":"Carwash",
    "L003":"Nachtwinkel",
    "L004":"restaurant",
    "L005":"Massage Salon",
    "L006":"Kamerverhuur",
    "L007":"Bar",
    "L50":"POI (Place Of Interest)",
    "M":"Modus Operandi",
    "M01":"Modus voor",
    "M011":"Voorbedachtheid",
    "M02":"Modus tijdens",
    "M021":"Aantal daders",
    "M022":"Binnendringen",
    "M023":"Gebruikt werktuig/voorwerp",
    "M024":"Buit",
    "M025":"Voertuig",
    "M0251":"huurvoertuig",
    "M026":"Voertuig met verborgen ruimte",
    "M03":"Modus na",
    "M04":"Gedrag dader",
    "M041":"Gebruik codetaal",
    "O":"Criminele organisatie structuur",
    "O01":"Leidinggevend/bevelend",
    "O011":"Chauffeur",
    "O02":"Uitvoerend lid",
    "O03":"Bevoordeelde",
    "O04":"Hulpkracht",
    "O05":"Facilitator",
    "O06":"Huurder",
    "O07":"Verhuurder",
    "O08":"Eigenaar",
    "O081":"Uitbater",
    "O09":"Pooier",
    "O10":"Dienster",
    "O11":"Element maffia",
    "O12":"Logistiek",
    "O13":"Communicatie",
    "O14":"cipiers",
    "P":"Persoonsbeschrijving",
    "P01":"Schijnbare leeftijd",
    "P011":"00-18 minderjarig",
    "P012":"18-25",
    "P013":"25-40",
    "P014":"40-65",
    "P015":"65+",
    "P02":"Huidskleur",
    "P021":"Blank",
    "P022":"Zwart",
    "P023":"Gelig",
    "P024":"Getaand",
    "P025":"Bruin",
    "P026":"Albino",
    "P027":"Oosters",
    "P027":"transgender",
    "P03":"Lengte",
    "P031":"Klein, minder dan 160 cm",
    "P032":"Middelgroot, tussen 160-180 cm",
    "P033":"Groot, Meer dan 180 cm",
    "P04":"Lichaamsbouw",
    "P041":"Mager",
    "P042":"Normaal",
    "P043":"Dik",
    "P044":"Atletisch",
    "P045":"Stevig",
    "P046":"Tatouage",
    "P047":"Litteken",
    "P048":"Ontbrekend lichaamsdeel",
    "P05":"Taal",
    "P051":"Nederlands",
    "P0511":"Lokaal accent",
    "P052":"Vreemde taal",
    "P06":"Stem",
    "P061":"Zacht",
    "P062":"Krachtig",
    "P063":"Stotterend",
    "P064":"Hees",
    "P07":"Ogen",
    "P071":"Kleur (combinatie met K)",
    "P072":"Helder",
    "P073":"Donker",
    "P074":"Bril",
    "P08":"Haardracht",
    "P081":"Kort",
    "P082":"Lang",
    "P083":"Kalend",
    "P084":"Kaal",
    "P0851":"Blond",
    "P0852":"Ros",
    "P0853":"Andere kleur (combinatie met K)",
    "P086":"Krullend",
    "P09":"Gelaat",
    "P091":"Pokdalig",
    "P092":"Sproeten",
    "P093":"Hazelip",
    "P094":"Zenuwtrek",
    "P095":"Snor",
    "P096":"Baard",
    "P097":"Bakkebaard",
    "P098":"Gebit",
    "P0981":"Gouden tanden",
    "P0982":"Zilveren tanden",
    "P0983":"Ontbrekende tand",
    "P0984":"Beugel",
    "P10":"Houding",
    "P101":"Kreupel/mank",
    "P102":"Dood / Overleden / Gestorven",
    "P11":"Kledij",
    "Pedofilie":"Pedofilie",
    "R":"Relationeel",
    "R01":"Vechtscheiding",
    "S":"Sporen",
    "S01":"DNA",
    "S011":"DNA",
    "S012":"Biologische sporen",
    "S02":"Vingersporen",
    "S03":"Schoeiselsporen",
    "S04":"Oorafdruk",
    "S05":"Haren",
    "S06":"Glassporen",
    "S07":"Bloedsporen",
    "S08":"Bandensporen",
    "S09":"Braaksporen",
    "S10":"Handschrift",
    "S11":"Nagelvuil",
    "S12":"Insnijdingen",
    "S13":"Vezels",
    "S14":"Sleepsporen",
    "S15":"Handpalmspoor",
    "S16":"Brandspoor/brandwonde",
    "S17":"Schotwonde",
    "S18":"Gunshot residues",
    "S19":"Handschoenspoor",
    "S20":"In bezit gestolen voorwerpen",
    "S21":"Wrijfspoor",
    "S22":"Kogelhulzen",
    "S5":"Telefonie / mastverkeer",
    "S51":"PGP",
    "T1":"Elementen omtrent dader",
    "T11":"Element ten laste dader",
    "T111":"Direct bewijs",
    "T112":"Indirect bewijs",
    "T12":"Motief / oorzaak dader",
    "T13":"Moraliteit dader",
    "T14":"Ten ontlaste verdachte",
    "T15":"Alibicontrole",
    "T2":"Elementen omtrent slachtoffer",
    "T21":"Belastend element slachtoffer",
    "T23":"Moraliteit slachtoffer",
    "T3":"Scenario",
    "T31":"Scenario wedersamenstelling",
    "T320":"Moord/doodslag",
    "T321":"Moord in opdracht",
    "T322":"Moord met enkelen",
    "T323":"Moord alleen",
    "T324":"Zelfmoord",
    "T5":"Negatief",
    "T6":"Positief",
    "T7":"Identificatie element",
    "TRA001":"Crypto (currencies, NFT's, BTC, Monero, Swapping services…)",
    "TRA002":"Darkweb",
    "TRA003":"Instant Messengers: Telegram, Wickr…",
    "TRA004":"Online banken (N26, Wise, Revolut etc.)",
    "TRA005":"Crime As A Service (CAAS)",
    "TRA006":"Anonimisatie en encryptie technieken",
    "V":"Voorwerpen",
    "V10":"Sleutels",
    "V20":"Juwelen",
    "V30":"Tas/koffer",
    "V50":"Containers",
    "V80":"Medicatie",
    "W":"Wapens",
    "W01":"Steekwapens",
    "W011":"Mes",
    "W012":"Bijl",
    "W02":"Vuurwapens",
    "W021":"Pistool / revolver",
    "W022":"Automatische vuurwapens (Uzi, Kalashnikov, ...)",
    "W023":"Gedempt wapen",
    "W024":"munitie",
    "W03":"Slagwapens",
    "W031":"Ijzeren staaf",
    "W032":"Boksbeugel",
    "W033":"Handboeien",
    "W1":"Wapens verkoop",
    "W2":"Wapens aankoop",
    "W3":"Wapens Bezit",
    "X10":"Provincie Limburg",
    "X11":"H L1 Limburg Regio Hoofdstad PZ",
    "X12":"H L2 Lommel PZ",
    "X13":"H L3 HANO PZ (Hamont-Achel-Neerpelt-Overpelt)",
    "X14":"H L4 Beringen - Ham - Tessenderlo PZ",
    "X15":"T LA Lanaken-Maasmechelen PZ",
    "X16":"H L6 Heusden-Zolder PZ",
    "X17":"H L7 Gingelom - Nieuwerkerken - Sint Truiden PZ",
    "X18":"H L8 Kempenland PZ (Leopoldsburg)",
    "X21":"T L1 Tongeren - Herstappe PZ",
    "X22":"T L2 Borgloon PZ",
    "X23":"T L3 BIHORI PZ (Bilzen-Hoeselt-Riemst)",
    "X24":"T L4 Voeren PZ",
    "X25":"T L5 Maasland PZ",
    "X26":"T L6 Carma PZ",
    "X27":"T L7 Noord-Oost Limburg PZ (oud)",
    "Z":"Aandachtspunten bij zoeking",
    "Z01":"Geen motorrijbewijs",
    "Z0901":"Piste 01",
    "Z0902":"Piste 02",
    "Z0903":"Piste 03",
    "Z0904":"Piste 04",
    "Z0905":"Piste 05",
    "Z0906":"Piste 06",
    "Z0907":"Piste 07",
    "Z0908":"Piste 08",
    "Z0909":"Piste 09",
    "Z0910":"Piste 10",
    "Z0911":"Piste 11",
    "Z0912":"Piste 12",
    "Z0913":"Piste 13",
    "Z0914":"Piste 14",
    "Z0915":"Piste 15",
    "Z0916":"Piste 16",
    "Z0917":"Piste 17",
    "Z0918":"Piste 18",
    "Z0919":"Piste 19",
    "Z0920":"Piste 20",
}
 
 